### ISSUE TITLE
open is not recognized as an internal or external command

### ISSUE THREAD

**Issue by sreich** [rtfpessoa/diff2html-cli#13]
└─[$] diff2html.cmd -i file -- difftest.diff                                                                                                              [14:09:15] 'open' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:507
    throw err;
    ^

Error: Command failed: open /tmp/diff.html
'open' is not recognized as an internal or external command,
operable program or batch file.

```
at checkExecSyncError (child_process.js:464:13)
at Object.execSync (child_process.js:504:13)
at Utils.runCmd (C:\Users\sreich\AppData\Roaming\npm\node_modules\diff2html-cli\src\utils.js:58:25)
at Diff2HtmlInterface.preview (C:\Users\sreich\AppData\Roaming\npm\node_modules\diff2html-cli\src\cli.js:106:11)
at onOutput (C:\Users\sreich\AppData\Roaming\npm\node_modules\diff2html-cli\src\main.js:157:9)
at Diff2HtmlInterface.getOutput (C:\Users\sreich\AppData\Roaming\npm\node_modules\diff2html-cli\src\cli.js:77:14)
at onInput (C:\Users\sreich\AppData\Roaming\npm\node_modules\diff2html-cli\src\main.js:145:7)
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

ideas on what's wrong?

**Comment by rtfpessoa** [comment]
I have some OS specific stuff in the code.
I will try to remove it. But I still have no way to test it.
If you can do some testing after the fix I would appreciate.

**Comment by sreich** [comment]
sounds good. how will i update to your changes? i installed using npm. 

java guy, never used node

**Comment by rtfpessoa** [comment]
As soon as I release something you just will have to do `npm update -g
diff2html-cli`.

**Comment by rtfpessoa** [comment]
@sreich can you update with `npm install -g diff2html-cli@1.4.0-windows1`
Since it is a pre-release I am not sure the update will take you there.

Then report back it is fixed. If can can check other features and report here, it would be really appreciated.

**Comment by sreich** [comment]
awesome! works perfectly now.

**Comment by rtfpessoa** [comment]
Closing this then :smile:
